
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ExemploCUP;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int ABREP = 10;
  public static final int IGUAL = 12;
  public static final int PTVG = 7;
  public static final int IMPRIME = 2;
  public static final int ABRECHV = 5;
  public static final int LITERAL = 17;
  public static final int ID = 15;
  public static final int TIPO = 14;
  public static final int EOF = 0;
  public static final int OPERADOR = 13;
  public static final int error = 1;
  public static final int NUMERO = 16;
  public static final int FECHAP = 11;
  public static final int VG = 9;
  public static final int NEW = 3;
  public static final int FECHACHV = 6;
  public static final int PARAM = 8;
  public static final int INICIO = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IMPRIME",
  "NEW",
  "INICIO",
  "ABRECHV",
  "FECHACHV",
  "PTVG",
  "PARAM",
  "VG",
  "ABREP",
  "FECHAP",
  "IGUAL",
  "OPERADOR",
  "TIPO",
  "ID",
  "NUMERO",
  "LITERAL"
  };
}

